//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ViewState.ProcessScheduler.Entities;

namespace ViewState.ProcessScheduler.Model
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ProcessSchedulerDbEntities : DbContext
    {
        public ProcessSchedulerDbEntities()
            : base("name=ProcessSchedulerDbEntities")
        {
        }

        public virtual void Commit()
        {
            base.SaveChanges();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Allocation> Allocations { get; set; }
        public virtual DbSet<ContactMethod> ContactMethods { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerAddressLink> CustomerAddressLinks { get; set; }
        public virtual DbSet<CustomerContactMethodLink> CustomerContactMethodLinks { get; set; }
        public virtual DbSet<CustomerOrder> CustomerOrders { get; set; }
        public virtual DbSet<CustomerOrderLine> CustomerOrderLines { get; set; }
        public virtual DbSet<CustomerOrderLineStatu> CustomerOrderLineStatus { get; set; }
        public virtual DbSet<CustomerOrderLineStatusHistory> CustomerOrderLineStatusHistories { get; set; }
        public virtual DbSet<CustomerOrderStatu> CustomerOrderStatus { get; set; }
        public virtual DbSet<CustomerOrderStatusHistory> CustomerOrderStatusHistories { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Design> Designs { get; set; }
        public virtual DbSet<Designer> Designers { get; set; }
        public virtual DbSet<DesignProcess> DesignProcesses { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<ResourceGroup> ResourceGroups { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StaffResourceGroupLink> StaffResourceGroupLinks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UnitProcess> UnitProcesses { get; set; }
        public virtual DbSet<UnitProcessStatu> UnitProcessStatus { get; set; }
        public virtual DbSet<UnitProcessStatusHistory> UnitProcessStatusHistories { get; set; }
        public virtual DbSet<UnitStatu> UnitStatus { get; set; }
        public virtual DbSet<UnitStatusHistory> UnitStatusHistories { get; set; }
        public virtual DbSet<WorksOrder> WorksOrders { get; set; }
        public virtual DbSet<WorksOrderStatu> WorksOrderStatus { get; set; }
        public virtual DbSet<WorksOrderStatusHistory> WorksOrderStatusHistories { get; set; }
    }
}
