//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewState.ProcessScheduler.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContactMethod()
        {
            this.CustomerContactMethodLinks = new HashSet<CustomerContactMethodLink>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ContactTypeID { get; set; }
        public string ContactMethodName { get; set; }
        public string ContactMethodDetails { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Active { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContactMethodLink> CustomerContactMethodLinks { get; set; }
    }
}
