//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewState.ProcessScheduler.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrderLine()
        {
            this.CustomerOrderLineStatusHistories = new HashSet<CustomerOrderLineStatusHistory>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid CustomerOrderID { get; set; }
        public System.Guid DesignID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public decimal PricePerUnit { get; set; }
    
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual Design Design { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrderLineStatusHistory> CustomerOrderLineStatusHistories { get; set; }
    }
}
