//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewState.ProcessScheduler.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContactMethodLink
    {
        public System.Guid ID { get; set; }
        public System.Guid CustomerID { get; set; }
        public System.Guid ContactMethodID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Active { get; set; }
    
        public virtual ContactMethod ContactMethod { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
