//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewState.ProcessScheduler.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DesignProcess()
        {
            this.UnitProcesses = new HashSet<UnitProcess>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid DesignID { get; set; }
        public System.Guid ProcessID { get; set; }
        public System.Guid DepartmentID { get; set; }
        public int ProcessTime { get; set; }
        public int ProcessOrder { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Active { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Design Design { get; set; }
        public virtual Process Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitProcess> UnitProcesses { get; set; }
    }
}
