//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewState.ProcessScheduler.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorksOrder()
        {
            this.Units = new HashSet<Unit>();
            this.WorksOrderStatusHistories = new HashSet<WorksOrderStatusHistory>();
        }
    
        public System.Guid ID { get; set; }
        public string WorksOrderNumber { get; set; }
        public System.Guid DesignID { get; set; }
        public int Quantity { get; set; }
        public System.Guid CustomerOrderLineID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
    
        public virtual Design Design { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorksOrderStatusHistory> WorksOrderStatusHistories { get; set; }
    }
}
